#Пример локер файла при помощи которого можно запустить GUI

FROM ubuntu:18.04
ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# Install system packages
RUN apt-get update && apt-get upgrade && apt-get install -y --no-install-recommends \
	build-essential \
	cmake \
	git \
	unzip \
	pkg-config \
	zlib1g-dev \
	libjpeg-dev \
	libjpeg8-dev \
	libjpeg-turbo8-dev \
	libpng-dev \
	libtiff-dev \
	libglew-dev \
	libavcodec-dev \
	libavformat-dev \
	libswscale-dev \
	libgtk2.0-dev \ 
	libgtk-3-dev \
	libcanberra-gtk* \
	python3-dev \
	python3-numpy \
	python3-pip \
	libxvidcore-dev \
	libx264-dev \
	libgtk-3-dev \
	libtbb2 \
	libtbb-dev \
	libdc1394-22-dev \
	libxine2-dev \
	gstreamer1.0-tools \
	libgstreamer-plugins-base1.0-dev \
	libgstreamer-plugins-good1.0-dev \
	libv4l-dev \
	v4l-utils \
	v4l2ucp \
	qv4l2 \
	libtesseract-dev \
	libxine2-dev \
	libpostproc-dev \
	libavresample-dev \
	libvorbis-dev \
	libfaac-dev \
	libmp3lame-dev \
	libtheora-dev \
	libopencore-amrnb-dev \
	libopencore-amrwb-dev \
	libopenblas-dev \
	libatlas-base-dev \
	libblas-dev \
	liblapack-dev \
	liblapacke-dev \
	libeigen3-dev \
	gfortran \ 
	libhdf5-dev \
	libprotobuf-dev \
	protobuf-compiler \
	libgoogle-glog-dev \
	libgflags-dev \	
    bzip2 \
    g++ \
    graphviz \
    libgl1-mesa-glx \
    libhdf5-dev \
    openmpi-bin \
    wget \
	htop \
    python3-tk && \
    rm -rf /var/lib/apt/lists/*
	
RUN mkdir /src
WORKDIR /src
COPY requirements.txt requirements.txt

RUN pip3 install --upgrade pip

RUN pip3 install --no-cache-dir -r requirements.txt

ENV DISPLAY=host.docker.internal:0.0

# Minimize image size 
RUN (apt-get autoremove -y; \
     apt-get autoclean -y)  

ENV QT_X11_NO_MITSHM=1

CMD ["bash"]
#CMD ["python", "show.py"]